### ISSUE TITLE
Should.Throw causes a FormatException

### ISSUE THREAD

**Issue by Allon-Guralnek** [shouldly/shouldly#378]
The following test fails with `System.FormatException : Input string was not in a correct format.`.

```csharp
[Test]
public void Shouldly_FormatException()
{
    Should.Throw<ArgumentException>(() => DoAsync(new object[] { }));
}

private Task DoAsync(object[] args)
{
    throw new Exception();
}
```

The full stack trace is below:

```
System.FormatException : Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Shouldly.MessageGenerators.ShouldThrowMessageGenerator.GenerateErrorMessage(IShouldlyAssertionContext context) in C:\projects\shouldly\src\Shouldly.Shared\MessageGenerators\ShouldThrowMessageGenerator.cs:line 32
   at Shouldly.ShouldlyMessage.GenerateShouldMessage() in C:\projects\shouldly\src\Shouldly.Shared\ShouldlyMessage.cs:line 271
   at Shouldly.ShouldlyMessage.ToString() in C:\projects\shouldly\src\Shouldly.Shared\ShouldlyMessage.cs:line 255
   at Shouldly.Should.ThrowInternal[TException](Func`1 actual, TimeSpan timeoutAfter, Func`1 customMessage, String shouldlyMethod) in C:\projects\shouldly\src\Shouldly.Shared\ShouldStaticClasses\ShouldThrowTask.cs:line 89
   at Shouldly.Should.Throw[TException](Func`1 actual, TimeSpan timeoutAfter, Func`1 customMessage) in C:\projects\shouldly\src\Shouldly.Shared\ShouldStaticClasses\ShouldThrowTask.cs:line 65
   at Shouldly.Should.Throw[TException](Func`1 actual, Func`1 customMessage) in C:\projects\shouldly\src\Shouldly.Shared\ShouldStaticClasses\ShouldThrowTask.cs:line 37
   at Shouldly.Should.Throw[TException](Func`1 actual) in C:\projects\shouldly\src\Shouldly.Shared\ShouldStaticClasses\ShouldThrowTask.cs:line 29
   at MyTests.Shouldly_FormatException() in D:\Git\Tests\MyTests.cs:line 105
```

If you change `new object[] { }` to `new object[0]` then the test produces the correct output:

```
Shouldly.ShouldAssertException : Task `DoAsync(new object[0])`
    should throw
System.ArgumentException
    but threw
System.Exception
```

I'm guessing the curly braces of the array initializer weren't escaped properly before passing them on to `string.Format()`.

**Comment by JosephWoodward** [comment]
Thanks for raising this @Allon-Guralnek. Had a few minutes spare in my lunch break to fix it :+1:
