### ISSUE TITLE
Error messages are not generated in Release build with full debug info

### ISSUE THREAD

**Issue by KAW24** [shouldly/shouldly#412]
Using the following example
```csharp
[Fact]
public void ShouldBeOneOf()
{
    var apu = new Person() { Name = "Apu" };
    var homer = new Person() { Name = "Homer" };
    var skinner = new Person() { Name = "Skinner" };
    var barney = new Person() { Name = "Barney" };
    var theBeSharps = new[] { homer, skinner, barney };

    apu.ShouldBeOneOf(theBeSharps);
}
```
I'm seeing the following message for assertion failures in a Release build where Debug Info is set to **full**
```
Error Message:
   Shouldly.ShouldAssertException : Shouldly uses your source code to generate its great error 
   messages, build your test project with full debug information to get better error messages
The provided expression
    should be one of
[Homer, Skinner, Barney]
    but was
Apu
Stack Trace:
   at Shouldly.ShouldBeTestExtensions.ShouldBeOneOf[T](T actual, T[] expected, Func`1 customMessage)
   at Shouldly.ShouldBeTestExtensions.ShouldBeOneOf[T](T actual, T[] expected)
   at ShouldlyBug.ShouldlyFixture.ShouldBeOneOf() in ShouldlyBug\ShouldlyFixture.cs:line 20
```
Note that source code information is displayed in the stack trace. I know this has worked previously so I wanted to see if I could trace out the source code information while debugging the test by adding a catch block around the assertion
```csharp
try
{
    apu.ShouldBeOneOf(theBeSharps);
}
catch (Exception ex)
{
    TraceFileInfo(ex);
    throw;
}
```
When I made this change I could see the source code information being written to the Output window but I could also see that the error message was now displayed correctly
```
Error Message:
   Shouldly.ShouldAssertException : apu
    should be one of
[Homer, Skinner, Barney]
    but was
Apu
Stack Trace:
   at Shouldly.ShouldBeTestExtensions.ShouldBeOneOf[T](T actual, T[] expected, Func`1 customMessage)
   at Shouldly.ShouldBeTestExtensions.ShouldBeOneOf[T](T actual, T[] expected)
   at ShouldlyBug.ShouldlyFixture.ShouldBeOneOf() in ShouldlyBug\ShouldlyFixture.cs:line 22
```
The code for `TraceFileInfo`, which is just lifted from the Shouldly source, seems to be changing the result. I also tried running the modified test without debugging and via vstest.console. In all cases the Release build produces the correct error message after `TraceFileInfo` is called.
```csharp
private static bool IsShouldlyMethod(MethodBase method) =>
    method.DeclaringType.GetCustomAttribute<ShouldlyMethodsAttribute>(true) != null;

private static void TraceFileInfo(Exception ex)
{
    var trace = new StackTrace(ex, true);
    var i = 0;
    var currentFrame = trace.GetFrame(i);
    var shouldlyFrame = default(StackFrame);
    while ((shouldlyFrame == null) || IsShouldlyMethod(currentFrame.GetMethod()))
    {
        if (IsShouldlyMethod(currentFrame.GetMethod()))
        {
            shouldlyFrame = currentFrame;
        }
        currentFrame = trace.GetFrame(++i);
    }
    Trace.WriteLine(
        $"File={currentFrame.GetFileName()}, " +
        $"Line={currentFrame.GetFileLineNumber()}, " +
        $"Column={currentFrame.GetFileColumnNumber()}");
}
```
Note that a Debug build always displays the correct error message. Has anyone else seen this issue with the most recent release of shouldly? Currently I'm not seeing useful error messages on Release builds.

My setup is
- Windows 7 SP1 x64
- Visual Studio 2015.3 Enterprise
- shouldly 2.8.2
- xunit 2.1.0
- xunit.runner.visualstudio 2.1.0

**Comment by JosephWoodward** [comment]
@KAW24 Thanks for your investigation into this, we're currently trying to track it down. (I appreciate this is an old issue!)
