### ISSUE TITLE
Filter stack trace

### ISSUE THREAD

**Issue by otto-gebb** [shouldly/shouldly#420]
## Summary

Filter the stack trace of `ShouldAssertException` to remove all lines that occur within the testing framework, like it is done in the [should](https://github.com/erichexter/Should/blob/master/src/Should.Core/Exceptions/AssertException.cs#L69) library.

## Details

Consider the following test

```cs
 [Fact]
 public void Test()
 {
     new[] { 1, 2 }.ShouldContain(3);
 }
```

Currently the test failure report looks like this
```
Result StackTrace:	
   at Shouldly.ShouldBeEnumerableTestExtensions.ShouldContain[T](IEnumerable`1 actual, T expected, Func`1 customMessage) in ...\ShouldBeEnumerableTestExtensions.cs:line 27
   at Shouldly.ShouldBeEnumerableTestExtensions.ShouldContain[T](IEnumerable`1 actual, T expected) in ...\ShouldBeEnumerableTestExtensions.cs:line 16
   at UnitTestProject1.UnitTest1.Test() in ...\UnitTest1.cs:line 13
Result Message:	
Shouldly.ShouldAssertException : new[] { 1, 2 }
    should contain
3
    but was actually
[1, 2]
```

Note the useless top two stack frames. I suggest to make it look like this:

```
Result StackTrace:
	at UnitTestProject1.UnitTest1.Test() in ...\UnitTest1.cs:line 13
Result Message:	
Shouldly.ShouldAssertException : new[] { 1, 2 }
    should contain
3
    but was actually
[1, 2]
```

**Comment by otto-gebb** [comment]
Here is how it could be implemented
(the code was borrowed from the "Should" project).

```diff
diff --git a/src/Shouldly/ShouldAssertException.cs b/src/Shouldly/ShouldAssertException.cs
index 2884d1f..ecc932b 100644
--- a/src/Shouldly/ShouldAssertException.cs
+++ b/src/Shouldly/ShouldAssertException.cs
@@ -1,20 +1,68 @@
using System;
+using System.Collections.Generic;
 
 namespace Shouldly
 {
 #if Serializable
     [Serializable]
 #endif
 #pragma warning disable 618
     public class ShouldAssertException : ChuckedAWobbly
 #pragma warning restore 618
     {
+        public static string FilterStackPrefix = "Shouldly.";
+
         public ShouldAssertException(string message) : base(message)
         {
         }
 
         public ShouldAssertException(string message, Exception innerException) : base(message, innerException)
         {
         }
+
+        public override string StackTrace
+        {
+            get
+            {
+                return FilterStackTrace(base.StackTrace);
+            }
+        }
+
+        public string UserMessage { get; protected set; }
+
+        protected static string FilterStackTrace(string stackTrace)
+        {
+            if (stackTrace == null)
+            {
+                return (string) null;
+            }
+            List<string> stringList = new List<string>();
+            foreach (string splitLine in SplitLines(stackTrace))
+            {
+                if (!splitLine.TrimStart().StartsWith("at " + FilterStackPrefix))
+                {
+                    stringList.Add(splitLine);
+                }
+            }
+            return string.Join(Environment.NewLine, stringList.ToArray());
+        }
+
+        private static IEnumerable<string> SplitLines(string input)
+        {
+            while (true)
+            {
+                int idx = input.IndexOf(Environment.NewLine);
+                if (idx >= 0)
+                {
+                    yield return input.Substring(0, idx);
+                    input = input.Substring(idx + Environment.NewLine.Length);
+                }
+                else
+                {
+                    break;
+                }
+            }
+            yield return input;
+        }
     }
 }

```

**Comment by jnm2** [comment]
This is a lot of noise, especially when it wraps in test runner UI:

```
   at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected, Func`1 customMessage)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected)
```

NUnit does something similar to this type of filter, too.

I've always wanted to try something like this:

<details>

```cs
public static void AssertAwesomely()
{
    var builder = new StringBuilder();
    WriteFilteredStackTrace(builder);
    var stackTrace = builder.ToString();
    // …
}

[MethodImpl(MethodImplOptions.NoInlining)] // In case something ever changes. Ensures that Assembly.GetExecutingAssembly()
                                           // is always the Shouldly assembly and that we can skip a frame.
internal static void WriteFilteredStackTrace(StringBuilder builder)
{
    var trace = new StackTrace(skipFrames: 1 /* As an optimization. Could be higher so long as callers are not themselves inlined. */);

    var shouldlyAssembly = Assembly.GetExecutingAssembly();

    for (var startIndex = 0; startIndex < trace.FrameCount; startIndex++)
    {
        var frame = trace.GetFrame(startIndex);
        if (frame.GetMethod().DeclaringType?.Assembly != shouldlyAssembly)
        {
            if (startIndex == 0)
            {
                builder.Append(trace);
            }
            else
            {
                var lines = new string[trace.FrameCount - startIndex];
                var neededCapacity = builder.Length;

                for (var i = 0; i < lines.Length; i++)
                {
                    var line = new StackTrace(trace.GetFrame(i + startIndex)).ToString();
                    lines[i] = line;
                    neededCapacity += line.Length;
                }

                builder.EnsureCapacity(neededCapacity);

                for (var i = 0; i < lines.Length - 1; i++)
                    builder.Append(lines[i]);
            }

            return;
        }
    }
}
```

</details>

**Comment by jnm2** [comment]
@JosephWoodward This issue hasn't seen much activity. Would a PR be welcome?

**Comment by JosephWoodward** [comment]
Hi @jnm2, sorry for the delayed response, I've been pretty busy lately. Yes a PR would certainly be most welcome.

**Comment by dennisroche** [comment]
I was just looking at a similar thing. Looking forward to the PR. 

It would be nice to filter the stack trace further using https://github.com/benaadams/Ben.Demystifier as `async` traces burn my eyes.

**Comment by jnm2** [comment]
@dennisroche The PR is up at https://github.com/shouldly/shouldly/pull/501.

I agree! That's less about filtering frames and more about pretty-printing each one, so maybe a new issue for that?

**Comment by dennisroche** [comment]
I agree. I'll wait until your PR is merged. 

For you PR, I think increasing the timeout is reasonable given the shared CI environment and parallel run of tests.

**Comment by jnm2** [comment]
Still waiting for a response to https://github.com/shouldly/shouldly/pull/501.

**Comment by JosephWoodward** [comment]
#501 has now been merged so this can be closed off, thanks for the great suggestion @otto-gebb

**Comment by jnm2** [comment]
@dennisroche, are you interested in opening that stack pretty-printing issue now?

**Comment by dennisroche** [comment]
@jnm2 i can open it if we're still think it is needed feature. 

the stack trace improvements that Demystifier provided were included into `netcore21`.  it would be nice for `net45` and `netcore20` users. 

https://github.com/benaadams/Ben.Demystifier

**Comment by dennisroche** [comment]
added bonus of Demystifier package is that it allows better stack trace walking of async tests. i have used it to get `ShouldMatchApproved` working much nicer in `netcore2`

**Comment by jnm2** [comment]
I don't think it's needed but I'd enjoy having it! :D

**Comment by dennisroche** [comment]
then upgrade to `netcore2.1`. it can significantly help debug errors in tests but it should be something that a team adds by extension point from shouldly.

**Comment by jnm2** [comment]
@dennisroche I'd use .NET Core if it was an option! Still going to be on .NET Framework for a while in many projects where I use Shouldly.

**Comment by JosephWoodward** [comment]
> added bonus of Demystifier package is that it allows better stack trace walking of async tests. i have used it to get `ShouldMatchApproved` working much nicer in `netcore2`

`ShouldMatchApproved` working on Linux or Mac? Is that in a personal repo? Wouldn't mind getting it supported on Mac or Linux.
