### ISSUE TITLE
With illegal character in PATH most tests fail

### ISSUE THREAD

**Issue by SteelFlow** [shouldly/shouldly#422]
I noticed most of my tests suddenly failed because of an "Illegal characters in path." error. 
After some digging i found out that DiffTool.GetFullPath does a Path.Combine with all my "PATH" environment variables and a hard coded filename.exe-string with known Diff Tools. 

I had some strange characters in one of my "PATH" environment variables which in turn made most of my tests fail. There ShouldBe (haha) som kind of exception handling when digging through files and varables on ones computers.

Stacktrace of the error
```
The type initializer for 'Shouldly.ShouldlyConfiguration' threw an exception.
The type initializer for 'Shouldly.Configuration.KnownDiffTools' threw an exception.
Illegal characters in path.
   at Shouldly.ShouldlyConfiguration.IsSourceDisabledInErrors()
   at Shouldly.Internals.ActualCodeTextGetter.GetCodeText(Object actual, StackTrace stackTrace) in C:\tmp\shouldly\shouldly\src\Shouldly\Internals\SourceCodeTextGetter.cs:line 32
   at Shouldly.ShouldlyAssertionContext..ctor(String shouldlyMethod, Object expected, Object actual, StackTrace stackTrace) in C:\tmp\shouldly\shouldly\src\Shouldly\Internals\ShouldlyAssertionContext.cs:line 50
   at Shouldly.ExpectedActualShouldlyMessage..ctor(Object expected, Object actual, Func`1 customMessage, String shouldlyMethod) in C:\tmp\shouldly\shouldly\src\Shouldly\ShouldlyMessage.cs:line 37
   at Shouldly.ShouldSatisfyAllConditionsTestExtensions.ShouldSatisfyAllConditions(Object actual, Func`1 customMessage, Action[] conditions) in C:\tmp\shouldly\shouldly\src\Shouldly\ShouldlyExtensionMethods\ShouldSatisfyAllConditionsTestExtensions.cs:line 38
   at Shouldly.ShouldSatisfyAllConditionsTestExtensions.ShouldSatisfyAllConditions(Object actual, Action[] conditions) in C:\tmp\shouldly\shouldly\src\Shouldly\ShouldlyExtensionMethods\ShouldSatisfyAllConditionsTestExtensions.cs:line 14
   at Shouldly.Tests.Strings.Verify.ShouldFail(Action action, String errorWithSource, String errorWithoutSource, Func`2 messageScrubber) in C:\tmp\shouldly\shouldly\src\Shouldly.Tests\Strings\Verify.cs:line 21
   at Shouldly.Tests.ShouldBe.ShouldBeScenarios.ComparingObjectWithStringFailure() in C:\tmp\shouldly\shouldly\src\Shouldly.Tests\ShouldBe\ShouldBeScenarios.cs:line 146
   at Shouldly.Internals.ActualCodeTextGetter.GetCodeText(Object actual, StackTrace stackTrace) in C:\tmp\shouldly\shouldly\src\Shouldly\Internals\SourceCodeTextGetter.cs:line 32
   at Shouldly.Configuration.KnownDiffTools.get_Instance()
   at Shouldly.Configuration.DiffToolConfiguration..ctor() in C:\tmp\shouldly\shouldly\src\Shouldly\Configuration\DiffToolConfiguration.cs:line 14
   at Shouldly.ShouldlyConfiguration..cctor() in C:\tmp\shouldly\shouldly\src\Shouldly\ShouldlyConfiguration.cs:line 24
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Shouldly.Configuration.DiffTool.<>c__DisplayClass10_0.<GetFullPath>b__2(String path) in C:\tmp\shouldly\shouldly\src\Shouldly\Configuration\DiffTool.cs:line 67
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Shouldly.Configuration.DiffTool.GetFullPath(String fileName) in C:\tmp\shouldly\shouldly\src\Shouldly\Configuration\DiffTool.cs:line 68
   at Shouldly.Configuration.DiffTool.Discover(String path) in C:\tmp\shouldly\shouldly\src\Shouldly\Configuration\DiffTool.cs:line 38
   at Shouldly.Configuration.DiffTool..ctor(String name, String path, ArgumentGenerator argGenerator) in C:\tmp\shouldly\shouldly\src\Shouldly\Configuration\DiffTool.cs:line 19
   at Shouldly.Configuration.KnownDiffTools..ctor() in C:\tmp\shouldly\shouldly\src\Shouldly\Configuration\KnownDiffTools.cs:line 12
   at Shouldly.Configuration.KnownDiffTools..cctor() in C:\tmp\shouldly\shouldly\src\Shouldly\Configuration\KnownDiffTools.cs:line 24
```

**Comment by SteelFlow** [comment]
I made a possible fix in PR #423

**Comment by Piedone** [comment]
Shouldn't this be closed due to the PR being merged @JosephWoodward?

**Comment by JosephWoodward** [comment]
Yes, you're correct. I missed this - thanks!
