### ISSUE TITLE
NullReferenceException thrown by failing test on non-Windows

### ISSUE THREAD

**Issue by martincostello** [shouldly/shouldly#531]
While writing some new tests in this PR justeat/JustEat.StatsD#127 (which currently fail due to a pending bug fix), I found that on OS X and Linux the tests are failing with a `NullReferenceException` from inside Shouldly at `Shouldly.Internals.ActualCodeTextGetter.ParseStackTrace(StackTrace trace)`, rather than the expected assertion failure that occurs on Windows.

I guess this is some artifact of the different PDB/symbol handling between Windows and other platforms?

## Windows Output

```sh
Error Message:
Shouldly.ShouldAssertException : result.Value<int>(config.Prefix + ".fish")
    should be
5
    but was
0

Additional Info:
    {
  "statsd.bad_lines_seen": 0,
  "statsd.packets_received": 99,
  "statsd.metrics_received": 99,
  "teststat": 2,
  "eb873a72a2544cc5854c33b0e60310b0.apple": 1,
  "eb873a72a2544cc5854c33b0e60310b0.bear": 5,
  "eb873a72a2544cc5854c33b0e60310b0.fish": 1,
  "eb873a72a2544cc5854c33b0e60310b0.green": 3,
  "eb873a72a2544cc5854c33b0e60310b0.red": 3,
  "72bb03633a314c9499c8ccd6f87f8615.apple": 1,
  "72bb03633a314c9499c8ccd6f87f8615.bear": 5,
  "72bb03633a314c9499c8ccd6f87f8615.fish": 1,
  "72bb03633a314c9499c8ccd6f87f8615.green": 3,
  "72bb03633a314c9499c8ccd6f87f8615.red": 3,
  "2584351a06f644d6a12f207f4827dac3.apple": 1,
  "2584351a06f644d6a12f207f4827dac3.bear": 5,
  "2584351a06f644d6a12f207f4827dac3.fish": 1,
  "2584351a06f644d6a12f207f4827dac3.green": 14,
  "2584351a06f644d6a12f207f4827dac3.red": -8,
  "89faba1ef69946109dfd2693fc6c5d33.apple": 1,
  "89faba1ef69946109dfd2693fc6c5d33.bear": 5,
  "89faba1ef69946109dfd2693fc6c5d33.fish": 1,
  "89faba1ef69946109dfd2693fc6c5d33.green": 14,
  "89faba1ef69946109dfd2693fc6c5d33.red": -8,
  "5bcaad2085074e61a305de17bffe2cfe.apple": 1,
  "5bcaad2085074e61a305de17bffe2cfe.bear": 5,
  "5bcaad2085074e61a305de17bffe2cfe.fish": 1,
  "5bcaad2085074e61a305de17bffe2cfe.green": 3,
  "5bcaad2085074e61a305de17bffe2cfe.red": 3,
  "4ae8f37db4bf4ea8a64f038de068ad6a.apple": 1,
  "4ae8f37db4bf4ea8a64f038de068ad6a.bear": 5,
  "4ae8f37db4bf4ea8a64f038de068ad6a.fish": 1,
  "4ae8f37db4bf4ea8a64f038de068ad6a.green": 14,
  "4ae8f37db4bf4ea8a64f038de068ad6a.red": -8,
  "0cb3f043a73c47ed865ece38ba6e118e.apple": 1
}
Stack Trace:
   at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected, Func`1 customMessage)
   at JustEat.StatsD.IntegrationTests.AssertMetrics(StatsDConfiguration config, IStatsDPublisher publisher) in C:\projects\justeat-statsd\src\JustEat.StatsD.Tests\IntegrationTests.cs:line 83
   at JustEat.StatsD.IntegrationTests.Can_Send_Metrics_To_StatsD_Using_Udp(String host, SocketProtocol socketProtocol, Boolean preferBufferedTransport) in C:\projects\justeat-statsd\src\JustEat.StatsD.Tests\IntegrationTests.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
```

## Linux Output

```sh
Error Message:
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at Shouldly.Internals.ActualCodeTextGetter.ParseStackTrace(StackTrace trace)
   at Shouldly.Internals.ActualCodeTextGetter.GetCodeText(Object actual, StackTrace stackTrace)
   at Shouldly.ShouldlyAssertionContext..ctor(String shouldlyMethod, Object expected, Object actual, StackTrace stackTrace)
   at Shouldly.ExpectedActualShouldlyMessage..ctor(Object expected, Object actual, Func`1 customMessage, String shouldlyMethod)
   at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
   at JustEat.StatsD.IntegrationTests.AssertMetrics(StatsDConfiguration config, IStatsDPublisher publisher) in /home/travis/build/justeat/JustEat.StatsD/src/JustEat.StatsD.Tests/IntegrationTests.cs:line 84
   at JustEat.StatsD.IntegrationTests.Can_Send_Metrics_To_StatsD_Using_Udp(String host, SocketProtocol socketProtocol, Boolean preferBufferedTransport) in /home/travis/build/justeat/JustEat.StatsD/src/JustEat.StatsD.Tests/IntegrationTests.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
```

## Build Links

  1. [Windows](https://ci.appveyor.com/project/justeattech/justeat-statsd/builds/19322096/tests)
  1. [Linux](https://travis-ci.org/justeat/JustEat.StatsD/jobs/438277934#L783)
  1. [OS X](https://travis-ci.org/justeat/JustEat.StatsD/jobs/438277935#L356)

**Comment by slang25** [comment]
Just to add some detail, I can recreate this when I do `dotnet test`, but when I run it from Rider I don't get the issue.

**Comment by JosephWoodward** [comment]
Looking into this at the moment, thanks for reporting it @martincostello

**Comment by SimonCropp** [comment]
@ealhomsi @martincostello can one of you supply a minimal and stand alone solution that reproduces this issue?

**Comment by SimonCropp** [comment]
given CI now passes on ubuntu, i will close this one. please let me know if it is still and issue
